[workspace]
resolver = "3"
members = ["crates/pelorus-spec", "xtask"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Pelorus Marine contributors <https://github.com/pelorus-marine>"]
repository = "https://github.com/pelorus-marine/specifications"
rust-version = "1.90.0"

[workspace.lints.rust]
unsafe_code = "forbid"
