//! Maintainer tasks for the specifications corpus — mdBook mirror + build.

use anyhow::{Context, Result};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() -> Result<()> {
    let mut args = env::args_os().skip(1);
    let cmd = args.next().unwrap_or_else(|| "help".into());

    match cmd.to_string_lossy().as_ref() {
        "gen-book" => gen_book(false),
        "book-build" => gen_book(true),
        "help" | "--help" | "-h" => {
            println!(
                "Pelorus specifications — xtask\n\
                 \n\
                 cargo run -p xtask -- gen-book    Mirror core/stream into book/src/generated (no mdbook)\n\
                 cargo run -p xtask -- book-build   gen-book + `mdbook build`\n"
            );
            Ok(())
        }
        other => anyhow::bail!("unknown command `{other}` — try `cargo run -p xtask -- help`"),
    }
}

fn repo_root() -> Result<PathBuf> {
    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR")?);
    Ok(manifest_dir
        .parent()
        .context("xtask must live in specifications/xtask")?
        .to_path_buf())
}

fn gen_book(run_mdbook: bool) -> Result<()> {
    let root = repo_root()?;
    let generated = root.join("book/src/generated");
    let core_dst = generated.join("core");
    let stream_dst = generated.join("stream");

    fs::remove_dir_all(&generated).ok();
    fs::create_dir_all(&core_dst).context("create core mirror dir")?;
    fs::create_dir_all(&stream_dst).context("create stream mirror dir")?;

    copy_md_dir(&root.join("core"), &core_dst)?;
    copy_md_dir(&root.join("stream"), &stream_dst)?;

    write_intro(&root, &generated)?;
    write_summary(&generated, &core_dst, &stream_dst)?;

    println!("Book source generated under {}", generated.display());

    if run_mdbook {
        let status = Command::new("mdbook")
            .current_dir(root.join("book"))
            .arg("build")
            .status()
            .context("spawn `mdbook` — install with `cargo install mdbook`")?;
        if !status.success() {
            anyhow::bail!("mdbook build failed with {status}");
        }
        println!("HTML output: {}", root.join("book/book").display());
    }

    Ok(())
}

fn copy_md_dir(src: &Path, dst: &Path) -> Result<()> {
    for entry in fs::read_dir(src).with_context(|| format!("read_dir {}", src.display()))? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) == Some("md") {
            let name = path.file_name().context("filename")?;
            fs::copy(&path, dst.join(name))
                .with_context(|| format!("copy {} -> {}", path.display(), dst.display()))?;
        }
    }
    Ok(())
}

fn sorted_md_names(dir: &Path) -> Result<Vec<String>> {
    let mut names = Vec::new();
    for entry in fs::read_dir(dir).with_context(|| format!("read_dir {}", dir.display()))? {
        let path = entry?.path();
        if path.extension().and_then(|s| s.to_str()) == Some("md") {
            names.push(
                path.file_name()
                    .context("name")?
                    .to_string_lossy()
                    .into_owned(),
            );
        }
    }
    names.sort();
    Ok(names)
}

fn write_intro(repo_root: &Path, generated: &Path) -> Result<()> {
    let spec_ver = read_manifest_version(&repo_root.join("crates/pelorus-spec/Cargo.toml"))
        .unwrap_or_else(|| "0.1.0-alpha.0".into());
    let body = format!(
        "# Pelorus specifications\n\
         \n\
         This book mirrors **[Pelorus Core](https://github.com/pelorus-marine/specifications/tree/main/core)** \
         and **[Pelorus Stream](https://github.com/pelorus-marine/specifications/tree/main/stream)** \
         Markdown from the same repository commit you built from. \
         **Normative intent** lives in Git history and pull requests; use this HTML build for reading and search.\n\
         \n\
         — Generated by `cargo xtask gen-book`. Rust crate [`pelorus-spec`](https://github.com/pelorus-marine/specifications/tree/main/crates/pelorus-spec) **{spec_ver}**.\n",
    );
    fs::write(generated.join("introduction.md"), body).context("write introduction.md")?;
    Ok(())
}

fn read_manifest_version(path: &Path) -> Option<String> {
    let text = fs::read_to_string(path).ok()?;
    text.lines().find_map(|line| {
        let line = line.trim();
        line.strip_prefix("version = ")
            .map(|rest| rest.trim().trim_matches('"').to_string())
    })
}

fn write_summary(generated: &Path, core_dir: &Path, stream_dir: &Path) -> Result<()> {
    let core_files = sorted_md_names(core_dir)?;
    let stream_files = sorted_md_names(stream_dir)?;

    let mut out = String::new();
    out.push_str("# Summary\n\n");
    out.push_str("- [Introduction](introduction.md)\n\n");
    out.push_str("# Pelorus Core\n\n");
    for name in &core_files {
        let title = chapter_title(name);
        out.push_str(&format!("- [{title}](core/{name})\n"));
    }
    out.push('\n');
    out.push_str("# Pelorus Stream\n\n");
    for name in &stream_files {
        let title = chapter_title(name);
        out.push_str(&format!("- [{title}](stream/{name})\n"));
    }

    fs::write(generated.join("SUMMARY.md"), out).context("write SUMMARY.md")?;
    Ok(())
}

fn chapter_title(filename: &str) -> String {
    let stem = filename.trim_end_matches(".md");
    let tail = stem.find('-').map(|i| &stem[i + 1..]).unwrap_or(stem);
    tail.split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
