name: Spell check

on:
  push:
    branches: [main, master]
    paths:
      - "**.md"
      - "**.rs"
      - "_typos.toml"
      - ".typos.toml"
      - "typos.toml"
      - ".github/workflows/typos.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "**.md"
      - "**.rs"
      - "_typos.toml"
      - ".typos.toml"
      - "typos.toml"
      - ".github/workflows/typos.yml"

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: crate-ci/typos@v1
